### ISSUE TITLE
Update PartFind integration

### ISSUE THREAD

**Issue by paddy-r** [paddy-r/StrEmbed-6-1#10]
* [x] #20
* [x] ~~Update PartFind installation within StrEmbed setup process~~ -> See #20
* [x] ~~Draw line when able to start integrating with newest version~~ -> See #20
* [x] Replace current frozen version of Partfind with downloaded version (i.e. version 0.0.1) -> may need tweaks as a couple of years old; provisionally done in https://github.com/thazlehurst/partfind/issues/15
* [x] Replace current Partfind installation process (via relative paths in ```part_compare```) with pip-based process using downloaded version (see above); may also go towards resolving #27; provisionally done in https://github.com/thazlehurst/partfind/issues/15
* [x] Remove and refactor hard path to Partfind folder in ```step_parse``` (see ```PARTFIND_FOLDER_DEFAULT```) -> commented line in ```step_parse```, seems to be redundant
* [x] #32 -> marking as done as transferred to new issue
