### ISSUE TITLE
Create and test Pyinstaller executable incorporating new Partfind setup

### ISSUE THREAD

**Issue by paddy-r** [paddy-r/StrEmbed-6-1#35]
Now that Partfind is installed via pip/conda env (see #10), must test whether Pyinstaller exe will run.

* [x] Add ```embed_images``` call to ```main``` with try-except to deal with exception in executable -> actually added exe/script switch instead; also add to documentation for now (i.e. "run ```main``` before trying to package") and see #2;
* [x] Add ```occ_patch_manual``` to ```main``` with try-except, as causes "Errno 2" in executable; also remove ```occ_patch_manual``` call from anywhere else (was only active in ```step_parse```) -> added exe/script switch instead; add instructions to documentation, see #2
* [x] ```FileNotFoundError``` in ```partgnn```: can't find ```trained_models``` folder: try adding exe/script switch in ```part_compare``` -> need to either (1) add exe/script switch in ```part_compare``` or (2) add ```--add-data=/path/to/file.dat:.``` option to Pyinstaller command (see [docs](https://pyinstaller.org/en/stable/runtime-information.html)) -> fixed in both directory and ```onefile``` exe formats
* [x] Also for above must include ```partfind``` explicitly in Pyinstaller build command as not in ```dist``` folder currently; this motivated #38 -> added as ```--hidden-import``` in Pyinstaller command
* [x] From #2: "Executable gives ```FileNotFoundError``` at runtime: folder ```partfindv1_frozen``` not found. Also see #35 as that may render this moot." -> entirely moot now as Partfind tidied up and installed via ```pip install```
* [x] Must add the above (```partfind``` installation) to docs
* [x] Ensure script/exe switch only done once (either in ```main``` or in ```part_compare```) -> actually fine, small switch in ```StrEmbed``` (was ```main```) for ```do_fixes``` and another in ```part_compare```, probably optimal as is, but start another issue to integrate ```do_fixes``` following work on consolidating non-app scripts, i.e. #39 -> issue #40
* [x] Change name of ```main``` -> ```StrEmbed``` and existing ```StrEmbed``` to ```gui``` or similar -> now ```gui```
* [x] Also add "create_exe.txt" with command (+Windows/Linux ```;``` vs. ```:``` in ```--add-data```) and remove long command from user manual -> plenty of notes there for future reference
* [x] Update docs to reflect all of the above, including how to capture output for debugging
