### ISSUE TITLE
Integrate "scenario_tester" functionality

### ISSUE THREAD

**Issue by paddy-r** [paddy-r/StrEmbed-6-1#60]
Check through ```scenario_tester``` and scripts called from there

* [x] Recreate results section of version 7/March 23 of BoM recon paper, i.e. results for five-piece puzzle, torch and railway carriages -> all checked in terms of calculating similarity scores via ```matching_strategy```, but see next point... -> done in #64
* [x] Add argument to ```matching_strategy``` (and whatever it calls) to grab/print all scores for analysis -> done in #66
* [x] Output results from the above to log file -> ~~logs to ```data/logs```~~ no, logs to go to ```output/logs```, also added to ```.gitignore``` in specific commit (b415867)
* [x] Capture all ```stdout``` ~~and ```stderr``` via decorator~~ (just ```stdout``` for now, and not bothered with decorator) -> text log file -> want to add ```stderr``` and decorator eventually, but not necessary for now -> see #67
* [x] ~~Combine functionality into larger "matching scenario" functionality/folder -> add folder~~ No, for now just refactored ```scenario_tester``` to be configurable via ```run_scenario``` method -> see #67
* [x] Add functionality for pipeline-like running with spec, via ```argparse```? -> marking as done as podded off to #67
* [x] ~~Add visualisation functionality for easy output of results;~~ roll into #43, no need for separate issue here
